### ISSUE TITLE
Version 7.0

### ISSUE THREAD

**Issue by eltonmorais** [X2Engine/X2CRM#164]
What about version 7.0?

**Comment by davidbhlm-github** [comment]
Hello team,

Do you have any update about versions 7.0 or 7.1? They don't appear in the repo or in [sourceforge](https://sourceforge.net/projects/x2engine/files/). 

I was also tracking [this case](http://community.x2crm.com/topic/3703-known-issues-with-ver-7-upgrade/) in your community forum. No updates since November 12th 

It would be great to have it working with PHP 7.1+.

Looking forward to your answer.

**Comment by pczupil** [comment]
There were a few issues with the open source version so we needed to delay the release dater slightly. We were not very vocal about this so our apologies. The 7.1 version is up on github and we are packaging it for SourceForge ASAP and should have it available by the end of the week.
